### ISSUE TITLE
Suggestion: Add flag to disable "auto subpackage resolving"

### ISSUE THREAD

**Issue by lorenmh** [Masterminds/glide#1063]
I am trying to install [`github.com/elastic/go-elasticsearch`](https://github.com/elastic/go-elasticsearch), which uses go modules. In their `go.mod` file, they name their package [`github.com/elastic/go-elasticsearch/v7`](https://github.com/elastic/go-elasticsearch/blob/7.x/go.mod#L1) (note the added `v7` for namespacing). 

However, this does not work with glide.

When I try to get glide to install `github.com/elastic/go-elasticsearch` to `vendor/github.com/elastic/go-elasticsearch/v7` (note the `v7` in the install path), with the following in `glide.yaml`:

```yaml
- package: github.com/elastic/go-elasticsearch/v7
  repo: git@github.com:elastic/go-elasticsearch
  version: v7.4.1
```

This _magically_ is changed to the following in the `glide.lock`:

```yaml
- name: github.com/elastic/go-elasticsearch
  version: d8acaa5faade05290d8b500b8f3892a378f2d2e7
  repo: git@github.com:elastic/go-elasticsearch
  subpackages:
  - v7
```

However, I do not want the `name` to change. I want it to stay as `github.com/elastic/go-elasticsearch/v7`. Ie, I want the following in my `glide.lock`:
```yaml
- name: github.com/elastic/go-elasticsearch/v7
  version: d8acaa5faade05290d8b500b8f3892a378f2d2e7
  repo: git@github.com:elastic/go-elasticsearch
```

**Suggestion**: please allow us to disable the automatic path-to-subpackage behavior. Ie, maybe the following `glide.yaml` should keep the `name` field the same in the lock file:

```yaml
- package: github.com/elastic/go-elasticsearch/v7
  repo: git@github.com:elastic/go-elasticsearch
  version: v7.4.1
  subpackages: []
```

or

```yaml
- package: github.com/elastic/go-elasticsearch/v7
  repo: git@github.com:elastic/go-elasticsearch
  version: v7.4.1
  auto_subpackage_resolution: false
```
