### ISSUE TITLE
SemVer constraint ignored

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#116]
My glide.yaml:

```
package: main
import:
  - package: github.com/Masterminds/vcs
  - package: github.com/Masterminds/semver
  - package: gopkg.in/yaml.v2
  - package: github.com/codegangsta/cli
  - package: k8s.io/kubernetes
    version: ~1.1
    subpackages:
      - /pkg
```

When I ran `glide up` and then checked in the `vendor/k8s.io/kubernetes` directory, I got this:

```
commit e310e619fc1ac4f3238bf5ebe9e7033bf5d47ee2
Author: Brendan Burns <bburns@google.com>
Date:   Fri Jul 31 21:21:58 2015 -0700

    Kubernetes version v1.0.2
```

$ glide --version
glide version 0.6.1-44-g48bbc53
