### ISSUE TITLE
Empty dependency

### ISSUE THREAD

**Issue by octopepper** [Masterminds/glide#118]
I encounter a problem with this dependency : code.google.com/p/goauth2/oauth (versioned by mercurial)

From an empty project/directory, for exemple "demo", running  `glide create` and `glide get code.google.com/p/goauth2/oauth` generates the following glide.yaml file :
```
package: main
import:
  - package: code.google.com/p/goauth2
    subpackages:
      - /oauth
```

Followed by `glide install` gives me an empty dependency/folder like that :
```
/demo $
 |-- glide.yaml
 |-- vendor
    |-- code.google.com
        |-- p
            |-- goauth2
               |-- [NOTHING HERE]
```

Maybe i'm doing something wrong ?
