### ISSUE TITLE
Glide scans for dependencies in README.md

### ISSUE THREAD

**Issue by favadi** [Masterminds/glide#191]
I test with a simple glide.yaml file:

```
package: .
import:
 - package: github.com/cyberdelia/go-metrics-graphite
```

There is no reference of `github.com/rcrowley/go-metrics` excepts in REAMDE.md.
The test script: https://github.com/favadi/glide-get-error/blob/234082dff7dc00d9d0326cbf5223e117405fd542/.travis.yml
Result: https://travis-ci.org/favadi/glide-get-error/builds/98750176

```
hash: cd85d213b54c39a4416ae610808a7003913f5ae8dcb25a90b130c4c89d19c8c1
updated: 2015-12-25T06:30:27.312023008Z
imports:
- name: github.com/cyberdelia/go-metrics-graphite
  version: 7e54b5c2aa6eaff4286c44129c3def899dff528c
- name: github.com/rcrowley/go-metrics
  version: 7839c01b09d2b1d7068034e5fe6e423f6ac5be22
  repo: https://github.com/rcrowley/go-metrics
- name: github.com/stathat/go
  version: 01d012b9ee2ecc107cb28b6dd32d9019ed5c1d77
  repo: https://github.com/stathat/go
devImports: []
```

As you can see the glide.lock files contains: `github.com/rcrowley/go-metrics` which is only represents in README.md of `github.com/cyberdelia/go-metrics-graphite`.

Glide should only scan for dependencies in .go files, not README.md.
