### ISSUE TITLE
glide up causes build break

### ISSUE THREAD

**Issue by dhanunjay** [Masterminds/glide#209]
Error 
------
../vendor/github.com/labstack/echo/echo.go:20:2: cannot find package "golang.org/x/net/http2" in any of:
	/home/dhanu/work/gocode/src/github.com/dschool/vendor/golang.org/x/net/http2 (vendor tree)
	/home/dhanu/.local/share/umake/go/go-lang/src/golang.org/x/net/http2 (from $GOROOT)
	/home/dhanu/work/gocode/src/golang.org/x/net/http2 (from $GOPATH)

Go env
---------
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dhanu/work/gocode"
GORACE=""
GOROOT="/home/dhanu/.local/share/umake/go/go-lang"
GOTOOLDIR="/home/dhanu/.local/share/umake/go/go-lang/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

glide.yaml
--------------
```yaml
package: github.com/dschool
import:
- package: github.com/labstack/echo
  version: "1.3"
```
glide version
-----------------
glide version 0.8.3

_Update: Added syntax highlighting to the yaml file for readability (mattfarina)._

**Comment by dhanunjay** [comment]
I have tried **glide get golang.org/x/net/http2** after **glide up** as mentioned above. But it did not pull http2. Can it be overwrite issue?

**Comment by mattfarina** [comment]
I found the problem. The `github.com/gin-gonic/gin` project requests the `golang.org/x/net` project at the version `621fff363a1d9ad7fdd0bfa9d80a42881267deb4`. This version is prior to the the inclusion of `http2`. This is a case of the first requestor wins. It is an example of why using commit ids to specify versions can cause problems.

Can you try the `glide.yaml` file:
```yaml
package: github.com/dschool
import:
- package: github.com/labstack/echo
  version: "1.3"
- package: golang.org/x/net
  version: master
```

By specifying the dependency here with a version it will be picked up with the newer version (tip of master).
