### ISSUE TITLE
Cgo based libraries take forever to run?

### ISSUE THREAD

**Issue by pyros2097** [Masterminds/glide#223]
I don't know whether is the is a glide issue or go vendor issue but it seems if I install a cgo based library with glide into my vendor packages and try to run my main file it takes a very long time to run but if i don't vendor these packages it runs in normal time.
This is the code I tried to run
```go
package main

import (
	"database/sql"
	_ "github.com/denisenkom/go-mssqldb"
	_ "github.com/mattn/go-sqlite3"
)
var msDB *sql.DB
func main() {
   println("StartingDB")
}
````

My glide.yaml file
```yaml
package: playlyfe.com/potential-connectors
import:
- package: github.com/denisenkom/go-mssqldb
- package: github.com/mattn/go-sqlite3
```
My GoENV
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/pyros2097/Code"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```
