### ISSUE TITLE
Snapshot packages version to glide.lock without updating

### ISSUE THREAD

**Issue by yeka** [Masterminds/glide#236]
When starting a new project, I usually use whatever is already there in my GOPATH.
Is there a way to snapshot all my current dependencies/packages and create glide.lock without upadating it?

I have two issues for using `glide update`:
1. It will fetch all packages and update it with the newest version. Sometimes I just want to use the existing version.
2. Fetching all packages could take forever for slow internet connection.

The closest thing to what I want is `glide update --use-gopath`.
But this still try to fetch/download from source even though the packages is already exists in GOPATH.
When I turn off my internet connection, it shows this
```console
$ glide update --use-gopath
[WARN] To use Glide, you must set GO15VENDOREXPERIMENT=1
[INFO] Fetching updates for github.com/labstack/echo.
[WARN] Download failed.
[WARN] Update failed for github.com/labstack/echo: exit status 128
[INFO] Scanning github.com/labstack/echo for dependencies.
[INFO] Fetching updates for github.com/labstack/gommon.
[WARN] Download failed.
[WARN] Skipped update github.com/labstack/gommon: exit status 128
....
```

The `glide.lock` it creates have some packages with missing version:
```yaml
hash: c3eedc6cc1549b2f8abf02a52fe3f5bd00501036dead950c14f9c15590898d63
updated: 2016-01-31T01:06:07.888800786Z
imports:
- name: github.com/labstack/echo
  version: fb926922bf6c2aac2bd90d26f341090e6c6103e8
  subpackages:
  - middleware
- name: github.com/labstack/gommon
  version: 43358a791be603db7175670d78abf544245f9941
- name: github.com/mattn/go-colorable
  version: 4af63d73f5bea08b682ad2cd198b1e607afd6be0
- name: github.com/mattn/go-isatty
  version: 56b76bdf51f7708750eac80fa38b952bb9f32639
- name: golang.org/x/crypto/ssh/terminal
  version: ""
- name: golang.org/x/net/context
  version: ""
- name: golang.org/x/net/http2
  version: ""
- name: golang.org/x/net/http2/hpack
  version: ""
- name: golang.org/x/net/websocket
  version: ""
devImports: []
```

I've check that `golang.org/x/*` exists in my GOPATH.
Here's the expected `glide.lock` (created using `glide update`):
```yaml
hash: c3eedc6cc1549b2f8abf02a52fe3f5bd00501036dead950c14f9c15590898d63
updated: 2016-01-31T00:58:40.969968987Z
imports:
- name: github.com/labstack/echo
  version: fb926922bf6c2aac2bd90d26f341090e6c6103e8
  subpackages:
  - middleware
- name: github.com/labstack/gommon
  version: 43358a791be603db7175670d78abf544245f9941
- name: github.com/mattn/go-colorable
  version: 4af63d73f5bea08b682ad2cd198b1e607afd6be0
- name: github.com/mattn/go-isatty
  version: 56b76bdf51f7708750eac80fa38b952bb9f32639
- name: golang.org/x/crypto
  version: 1f22c0103821b9390939b6776727195525381532
- name: golang.org/x/net
  version: 04b9de9b512f58addf28c9853d50ebef61c3953e
- name: golang.org/x/text
  version: 6fc2e00a0d64b1f7fc1212dae5b0c939cf6d9ac4
devImports: []
```

Taking a close look at that `glide.lock` from `glide update --use-gopath`, it successfully snapshot the version of packages from github.com but not the packages from golang.org.
Might it be a bug?
