### ISSUE TITLE
glide up shows "No subpackages declared. Skipping ...", even when there are subpackages

### ISSUE THREAD

**Issue by arschles** [Masterminds/glide#242]
My glide.yaml:

```yaml
package: main
ignore:
- appengine
import:
- package: gopkg.in/natefinch/lumberjack.v2
  version: 600ceb4523e5b7ff745f91083c8a023c2bf73af5
- package: gopkg.in/olivere/elastic.v2
  version: 444684342d4c12c7c05bed13bd249034370840a9
- package: gopkg.in/tomb.v1
  version: dd632973f1e7218eb1089048e0798ec9ae7dceb8
- package: gopkg.in/v2/yaml
  version: 53feefa2559fb8dfa8d81baad31be332c97d6c77
- package: gopkg.in/yaml.v2
  version: 53feefa2559fb8dfa8d81baad31be332c97d6c77
- package: github.com/deis/pkg
  version: f63d9718b86f17c9320f838fb3eb6039cadb9691
  subpackages:
  - /aboutme
  - /utils
- package: github.com/minio/minio-go
  version: 0.2.5
```

Abbreviated output from `glide up` (notice the `subpackages` declared above on the erroneus package listed below):

```console
[INFO] Resolving imports
[INFO] No subpackages declared. Skipping github.com/deis/pkg.
```

Found on a `glide` binary built from https://github.com/Masterminds/glide/commit/91f83358eecdff6abe35d49baf755c5576661a2a
