### ISSUE TITLE
Support for packages per OS or Arch

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#25]
Should we add support for per-architecture and per-OS dependencies?

Some packages only provide functionality for a particular OS or a particular architecture. I'm thinking we could add support for this condition:

```yaml
import:
    - package: my/windows/package
      os: windows
    - package: another/package
      os:
        - linux
        - solaris
```

Or something like that.

PROS:
- It makes it easier to support builds on different platforms with just one glide file

CONS:
- It makes the cross-compiling case potentially more difficult, though we could add a flag to fetch all dependencies regardless of OS or arch.

Thoughts?

**Comment by technosophos** [comment]
I am working on implementing this, with YAML being:

```yaml
- package: some/package
  os:
    - linux
  arch:
    - amd64
```

Like the subpackage directive, we can shorten the above to:

```
- package: some/package
  os: linux
  arch: amd64
```

In either case, `os` and `arch` are whitelists. When they are present and non-empty, the package will only be fetched if it's `runtime.GOOS` is in the `os` list and its `runtime.GOARCH` is in `arch`.
