### ISSUE TITLE
glide init adds sub packages of top level package to imports

### ISSUE THREAD

**Issue by james-lawrence** [Masterminds/glide#259]
```bash
glide init
```
```yml
package: bitbucket.org/soandso/package
import:
- package: bitbucket.org/soandso/package
  subpackages:
   - A
   - B
   - C
```
then it complains about these sub packages not being in vendor....
it also attempts to fetch the top level package because its in the import set.

is there a reason for this? I thought it would ignore any packages root at the top level package.
