### ISSUE TITLE
go build & go install error 

### ISSUE THREAD

**Issue by xuqingfeng** [Masterminds/glide#261]
```
package bitbucket.org/jsxqf/hpack-cli                                     
imports bitbucket.org/jsxqf/hpack-cli/vendor/github.com/Sirupsen/logrus: must be imported as github.com/Sirupsen/logrus
package bitbucket.org/jsxqf/hpack-cli           
imports bitbucket.org/jsxqf/hpack-cli/vendor/github.com/codegangsta/cli: must be imported as github.com/codegangsta/cli
```

PS. 
`export GO15VENDOREXPERIMENT=1`is added to .zshrc
go version go1.5.3 darwin/amd64
glide version 0.8.2

**Comment by mhoglan** [comment]
you should try with the latest `glide` from source 

this sounds like an issue with a nested vendor scenario and you could probably resolve it by removing the nested vendor directory in the dependency and flattening out the dependencies at the top level.   Such as adding `Sirupsen/logrus` and `codegangsta/cli`to your `glide.yaml` so they are top level dependencies.

**Comment by technosophos** [comment]
If @mhoglan's suggestion doesn't fix the problem,  it would be helpful to be able to see the `import()` line that is causing those errors.

**Comment by xuqingfeng** [comment]
@technosophos @mhoglan 

`glide.yaml`

```yaml
package: bitbucket.org/jsxqf/hpack-cli
import:
  - package: github.com/Sirupsen/logrus
    version: 0.9.0
    repo: git@github.com:Sirupsen/logrus.git
  - package: github.com/codegangsta/cli
    version: master
    repo: git@github.com:codegangsta/cli.git
```

`main.go`

```go

import (
    "bitbucket.org/jsxqf/hpack-cli/util"
    log "bitbucket.org/jsxqf/hpack-cli/vendor/github.com/Sirupsen/logrus"
    "bitbucket.org/jsxqf/hpack-cli/vendor/github.com/codegangsta/cli"
    "os"
    "time"
)
```

PS. 

`GOPATH`: /Users/xuqingfeng/Godir

`export GO15VENDOREXPERIMENT=1` is removed

Also note that I update golang to 1.6 and glide to 0.9.0, but still can't make it work.
