### ISSUE TITLE
Running `glide up` does not update glide.lock with latest revision of private repo

### ISSUE THREAD

**Issue by ryanwalls** [Masterminds/glide#327]
I have a private repo that I have as a dependency of my project.  When I push new code to the private repo and then run `glide up` in the project, the glide.lock file is not updated to the latest revision.  I've worked around it by manually updating the lock file.  

Glide version: 0.9.1
Go version: 1.6

**Comment by russmatney** [comment]
I'm seeing similar behavior, just want to add that I'm seeing `Cannot detect VCS` errors on the private repo's subpackages. The error is fair, but I wouldn't expect that to prevent a `glide.lock` update for the rest of the packages, especially when `vendor/` updates just fine.

**Comment by technosophos** [comment]
I have seen this error, and have worked around it by using `version: master` in the `glide.yaml` file. That, however, is not the intended behavior. We need to get a fix for this into Glide.

**Comment by technosophos** [comment]
@russmatney Are you setting the VCS fields (`vcs`, `repo`) in the `glide.yaml` file? 
https://github.com/Masterminds/glide/blob/master/docs/glide.yaml.md

**Comment by russmatney** [comment]
@technosophos glide.yml is as such:

```
package: myproj.domain/namespace/proj
import:
- package: myproj.domain/namespace/firstdep
  vcs: git
//etc
```

The errors/warnings are for `firstdep`'s subpackages, which may not have a detectable vcs as they belong to `firstdep`'s git repo. Ideally they'd throw "soft" warnings rather than fail the whole glide.lock update – all I need is `firstdep` to update itself, assuming that's the intended behavior. For now I'm updating the version in the .lock file by hand, but can move to the `version: master` fix.

**Comment by technosophos** [comment]
I think @mattfarina may know why the VCS error is showing up. But the reason it's a stopping condition is that once a VCS can't be updated, we can't guarantee the consistency of the version tree anymore.

Let me know if setting `version: master` works.

**Comment by mattfarina** [comment]
@russmatney Glide keeps compatibility with `go get` on remote package names. If you go to the `import` section on the [`glide.yaml` docs](http://glide.readthedocs.org/en/latest/glide.yaml/) you'll see the rules listed under the `package` property for a name.

@technosophos should we keep `go get` compatibility? This is one of those places I'd love to have a lively conversation on.

**Comment by technosophos** [comment]
@mattfarina it is the VCS error that we're trying to ferret out

**Comment by sdboyer** [comment]
@mattfarina sorry, why wouldn't we keep keep godep compat? the only reason i can imagine is because that means including the `.git` infix for custom domains, and that feels redundant with also having the `vcs: git` property. what am i missing?

**Comment by mattfarina** [comment]
@sdboyer godep compat? Do you mean `go get` compat?

**Comment by sdboyer** [comment]
@mattfarina sorry, yes, butterfingers

**Comment by russmatney** [comment]
@technosophos @mattfarina my mistake – I misread the errors and jumped to the wrong conclusion, namely that the private repo VCS errors were preventing the `glide.lock` write. The issue is caused by an actual error in resolving `x/net/context`, same as https://github.com/Masterminds/glide/issues/373.

The private repo VCS warnings is a result of the state of gogs and go-import metadata: https://github.com/gogits/gogs/issues/2825

I'm seeing proper `glide.lock` updates now (if the x/net version is set to an earlier commit, that is).

**Comment by atombender** [comment]
We're seeing something that looks like this problem, but it doesn't happen for me, only for my colleagues. [Here](https://gist.github.com/atombender/23d1e5ce01d6453be684f4d7f58ff277) are the outputs of the exact same commands on my machine (`good.txt`) and one of theirs (`bad.txt`).

We're using the same version of Go and Glide. It's all on OS X. The only difference seems to be that my colleagues check out Git repos using the `git` protocol, whereas I use `https`.

Setting `version: master` fixes the issue.

**Comment by atombender** [comment]
I can reproduce it consistently now, but I'm not sure if it represent the original failure scenario exactly. First, I create this `glide.yaml` in a clean directory, with one package:

```yaml
package: github.com/t11e/glidebug
import:
- package: github.com/aws/aws-sdk-go
  version: 6f62fc3ff9aa98c629b350376825cda566658d75
  subpackages:
  - aws
  - aws/awserr
  - aws/session
  - service/s3
```

Then I run `glide install`. Everything good so far.

Then I remove `version: 6f62...` and run `glide up`. Now my lock file is:

```
hash: 1ac04a04efbc1f1153bf98b3876e0e722b49e5b702a87bf0dde64e0212d1e702
updated: 2016-05-06T14:35:39.336813296-04:00
imports:
- name: github.com/aws/aws-sdk-go
  version: 6f62fc3ff9aa98c629b350376825cda566658d75
  subpackages:
  - aws
  - aws/awserr
  - aws/session
  - service/s3
devImports: []
```

Notice old version still remains. `glide up` does not refresh anything.
