### ISSUE TITLE
When I fork a github repo and use glide create, the package will be my fork repo's link

### ISSUE THREAD

**Issue by Akagi201** [Masterminds/glide#330]
The origin repo is github.com/winlinvip/bms4upyun. When I forked it, it turns to be github.com/Akagi201/bms4upyun

Then when I use glide create in my forked repo. the glide.yaml will be

```
package: github.com/Akagi201/bms4upyun
import:
- package: github.com/koding/cache
- package: github.com/mediocregopher/radix.v2
  subpackages:
  - pool
  - redis
- package: github.com/ossrs/go-oryx-lib
  subpackages:
  - logger
```

The `package: ` line should be `package: github.com/winlinvip/bms4upyun`
