### ISSUE TITLE
Proposal: Support for build flags in lock file

### ISSUE THREAD

**Issue by technosophos** [Masterminds/glide#333]
I'm still trying to figure out the best way to handle the seemingly intractable issue of build flags. Here's one way we might consider doing it:

- Alter the glide.lock to store more than one set of dependencies
- Store dependencies per-buildflag set.
- Build the lists lazily

Here's an example of what the file format might look like:

```yaml
hash: 1b76070c56de9f698ebbd32b2f36d2c972888fc0793f7843b0925e4faca65d4b
updated: 2016-03-07T15:05:34.774169565-05:00
- build:
    - GOOS: linux
    - GOARCH: amd64
    - tags:
      - foo
  imports:
  - name: github.com/codegangsta/cli
    version: c31a7975863e7810c92e2e288a9ab074f9a88f29
  - name: github.com/Masterminds/semver
    version: 513f3dcb3ecfb1248831fb5cb06a23a3cd5935dc
  - name: github.com/Masterminds/vcs
    version: 242477a09d9db06a848c5305525168f042d96871
  - name: gopkg.in/yaml.v2
    version: f7716cbe52baa25d2e9b0d0da546fcf909fc16b4
  devImports: []
- build:
    - GOOS: mach
    - GOARCH: amd64
  imports:
  - name: github.com/codegangsta/cli
    version: c31a7975863e7810c92e2e288a9ab074f9a88f29
  devImports: []
```

The example above represents the dependencies on two different sets of build flags. (I just made up the dependencies -- you can ignore the specifics of those).

The first one is for a `GOOS=linux GOARCH=amd64 go build -tags foo` and the second one would be for `GOOS=mach GOARCH=amd64 go build`.

In most cases, the lists will be duplicates... but I think that is okay. The size of the lock file is not really a big concern.

Now, instead of generating all possible versions of the file for every Glide operation, we could just generate the build-specific version of the lock for whatever the CLI specified. So if I `glide up`, it will update Glide.yaml, but only update the section of glide.lock that has my particular architecture in it.

Perhaps we'd want to store hash and date inside of each build section (instead of at the top) so that the CLI could correctly flag cases where the top-level YAML differs from some subsection of the lock.

What we gain:
- We don't have to solve for every architecture/os/flags combination each time
- Only architectures/tag combos that people actually use are present in the lock file

The big drawbacks:
- Cross-platform reproducibility becomes the responsibility of the person running `glide up`. Basically, users must treat `glide up` like a cross-compile if they want to make sure that all of the versions are the same between different arch/flag combinations
- This is a _major_ change to the lock architecture
