### ISSUE TITLE
Find outdated dependencies and update them

### ISSUE THREAD

**Issue by ernestoalejo** [Masterminds/glide#356]
To help when updating dependencies. Right now I have to manually check if there is a new commit, get the hash, write it and update. A command like `npm outdated` would be very useful.

At least reinstall the dependency from zero if asked to do it; e.g.: `glide get foo.com/bar` to get the latest version, like the first time I used it. Currently it warns: "Package "foo.com/bar" is already in glide.yaml. Skipping". It does not have to be `get`, another different command can be added too.

**Comment by mattfarina** [comment]
A couple things.

1. If no version is specified the `glide.yaml` file the default is to follow the tip of the default branch.
2. Running `glide update` will resolve the dependency tree and versions based on the `glide.yaml` file. If it's following the tip of master on a project it will update to the latest commit. The new state will be written to the `glide.lock` file.

You shouldn't have to remove a dependency to update it. Glide does that for you.

**Comment by ernestoalejo** [comment]
That is precisely what I want `glide` to do; but it's not the current behaviour. Running `glide update` with the following pair of files does nothing to update to the latest commit (b2c7a7da...).

glide.yaml:
```yaml
package: tt
import:
- package: github.com/juju/errors
```

glide.lock:
```yaml
hash: c5d0b5564bb639895d120e9a72eb397a6eb6efc23a772e808c9a49e20db395de
updated: 2016-03-28T02:44:51.503697917+02:00
imports:
- name: github.com/juju/errors
  version: 797449fa4bdba2948dfc581cdc3acf625272a8d6
devImports: []
```

```shell
  glide update
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/juju/errors.
[INFO] Resolving imports
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references for remaining imports
[INFO] Project relies on 1 dependencies.

# Still on 797449...

  glide install
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/juju/errors.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[INFO] Setting version for github.com/juju/errors to 797449fa4bdba2948dfc581cdc3acf625272a8d6.
```

**Comment by mattfarina** [comment]
I'm rather confused. I just started with this `glide.yaml`:

```yaml
package: tt
import:
- package: github.com/juju/errors
```
It was created using `glide init` on the codebase. I then ran `glide update` and it produced the following `glide.lock` file:
```yaml
hash: c5d0b5564bb639895d120e9a72eb397a6eb6efc23a772e808c9a49e20db395de
updated: 2016-03-27T20:59:57.085268681-04:00
imports:
- name: github.com/juju/errors
  version: b2c7a7da5b2995941048f60146e67702a292e468
devImports: []
```
This does have the latest commit. This is using Glide 0.10.1. I wish I could reproduce your issue.

Does your git client have a cache? Glide drops down to `git` to make calls to GitHub.
