### ISSUE TITLE
Strip VCS in YAML file

### ISSUE THREAD

**Issue by schickling** [Masterminds/glide#362]
It would be really nice to specify on a package level whether you'd want to strip the VCS or not.

The use case I'm imagining here is: I want to just strip the VCS for private repos in order to have them available all the time and leave it for public dependencies.

**Comment by technosophos** [comment]
Interesting idea. We'll have to think about this. Do you have a suggestion for the syntax?

**Comment by schickling** [comment]
What about:

```yml
- package: github.com/aws/aws-sdk-go
  strip_vcs: true
  subpackages:
  - aws
  - aws/credentials
  - aws/session
  - service/s3
```

`strip_vcs` would be `false` as default
