### ISSUE TITLE
glide install appears to ignore the OS constraint when checking out versions.

### ISSUE THREAD

**Issue by davecgh** [Masterminds/glide#409]
```bash
$ glide -v
glide version 0.10.2-47-ge73500c
```

As the title indicates, `glide install` appears to ignore the OS constraint when checkout out the revisions specified by `glide.lock`.

For example, assume the `glide.lock` file contains the following:

```yaml
- name: github.com/btcsuite/winsvc
  version: f8fb11f83f7e860e3769a08e6811d1b399a43722
  os:
  - windows
  subpackages:
  - eventlog
  - mgr
  - svc
  - registry
  - winapi
```

When performing `glide install` against a fresh directory, the following happens:

> [ERROR] Failed to set version on github.com/btcsuite/winsvc to f8fb11f83f7e860e3769a08e6811d1b399a43722: open /home/travis/gopath/src/github.com/btcsuite/btcd/vendor/github.com/btcsuite/winsvc: no such file or directory

The cause appears to be that the repository correctly is not fetched, as expected, however, the code then tries to checkout the specific revision in the repository that doesn't exist.
