### ISSUE TITLE
Sub package dependencies not being pulled into vendor directory

### ISSUE THREAD

**Issue by Integralist** [Masterminds/glide#427]
I have Docker running in a CI environment and I'm trying to build a binary of my project which has dependencies vendored with Glide.

The problem is that Glide is unable to locate sub dependencies.

For example, I have a project "foo" that's vendored with Glide. One of the dependencies is "bar" (in this case: https://github.com/Integralist/go-elasticache) and its own vendoring is handled by Glide also. This package "bar" pulls in another package "baz" (in this case: https://github.com/Integralist/go-findroot) and once again that package's vendoring is handled by Glide.

Looking at my project tree I have:

```
│       │   ├── integralist
│       │   │   └── go-elasticache
│       │   │       ├── LICENSE
│       │   │       ├── Makefile
│       │   │       ├── README.md
│       │   │       ├── elasticache
│       │   │       │   ├── elasticache.go
│       │   │       │   └── elasticache_test.go
│       │   │       ├── glide.lock
│       │   │       ├── glide.yaml
│       │   │       └── vendor
│       │   │           └── github.com
│       │   │               ├── bradfitz
│       │   │               │   └── gomemcache
│       │   │               └── integralist
│       │   │                   └── go-findroot
```

You can see that the package content isn't actually pulled in by Glide?

To work around this I'm having to manually `glide get <package>` for both `bradfitz/gomemcache` and `integralist/go-findroot` so they're vendored up at the top of my vendor directory instead.

Luckily I don't have lots of sub packages, but already with two sub packages I'm finding this tedious having to manually pull them in.

**Comment by sdboyer** [comment]
This kind of flattening is something `glide` should be doing already...it's not immediately clear to me why it isn't now. Do things get saner if you run with `--update-vendored --strip-vcs --strip-vendor`?

**Comment by Integralist** [comment]
If I run `glide install --update-vendored --strip-vcs --strip-vendor` then my tree looks like:

```
.
├── stuff and folders
├── glide.lock
├── glide.yaml
├── main.go
└── vendor
    ├── github.com
    │   ├── bbc
    │   │   └── mozart-api-common
    │   │       ├── Godeps
    │   │       │   ├── Godeps.json
    │   │       │   └── Readme
    │   │       ├── README.md
    │   │       ├── caching
    │   │       │   ├── cache.go
    │   │       │   ├── mock_cache.go
    │   │       │   └── redis_cache.go
    │   │       ├── logger
    │   │       │   ├── logger.go
    │   │       │   └── statsd_hook.go
    │   │       └── storage
    │   │           ├── error.go
    │   │           ├── mock_storage.go
    │   │           ├── s3_storage.go
    │   │           └── storage.go
    │   ├── bradfitz
    │   │   └── gomemcache
    │   │       ├── LICENSE
    │   │       ├── README.md
    │   │       └── memcache
    │   │           ├── memcache.go
    │   │           ├── memcache_test.go
    │   │           ├── selector.go
    │   │           └── selector_test.go
    │   ├── integralist
    │   │   └── go-elasticache
    │   │       ├── LICENSE
    │   │       ├── Makefile
    │   │       ├── README.md
    │   │       ├── elasticache
    │   │       │   ├── elasticache.go
    │   │       │   └── elasticache_test.go
    │   │       ├── glide.lock
    │   │       └── glide.yaml
    │   ├── joho
    │   │   └── godotenv
    │   │       ├── LICENCE
    │   │       ├── README.md
    │   │       ├── autoload
    │   │       │   └── autoload.go
    │   │       ├── cmd
    │   │       │   └── godotenv
    │   │       │       └── cmd.go
    │   │       ├── fixtures
    │   │       │   ├── equals.env
    │   │       │   ├── exported.env
    │   │       │   ├── plain.env
    │   │       │   └── quoted.env
    │   │       ├── godotenv.go
    │   │       ├── godotenv_test.go
    │   │       └── wercker.yml
    │   └── julienschmidt
    │       └── httprouter
    │           ├── LICENSE
    │           ├── README.md
    │           ├── path.go
    │           ├── path_test.go
    │           ├── router.go
    │           ├── router_test.go
    │           ├── tree.go
    │           └── tree_test.go
    └── gopkg.in
        ├── godo.v2
        │   ├── CHANGES-V2.md
        │   ├── Gododir
        │   │   └── main.go
        │   ├── LICENSE
        │   ├── Makefile
        │   ├── README.md
        │   ├── VERSION.go
        │   ├── book
        │   │   ├── README.md
        │   │   ├── SUMMARY.md
        │   │   ├── getting_started
        │   │   │   ├── README.md
        │   │   │   └── locating_maingo.md
        │   │   ├── installation
        │   │   │   └── README.md
        │   │   └── tasks
        │   │       └── README.md
        │   ├── cmd
        │   │   ├── example
        │   │   │   ├── handler.go
        │   │   │   └── main.go
        │   │   └── godo
        │   │       └── main.go
        │   ├── cmd.go
        │   ├── context.go
        │   ├── doc.go
        │   ├── env.go
        │   ├── env_test.go
        │   ├── exec.go
        │   ├── exec_test.go
        │   ├── fileWrapper.go
        │   ├── glob
        │   │   ├── fileAsset.go
        │   │   ├── glob.go
        │   │   ├── glob_test.go
        │   │   ├── test
        │   │   │   ├── foo.sh
        │   │   │   ├── foo.txt
        │   │   │   └── sub
        │   │   │       ├── sub
        │   │   │       │   ├── subsub1.txt
        │   │   │       │   └── subsub2.html
        │   │   │       ├── sub1.txt
        │   │   │       └── sub2.txt
        │   │   ├── test2
        │   │   │   ├── main.css
        │   │   │   └── main.js
        │   │   ├── watchCriteria.go
        │   │   └── watchCriteria_test.go
        │   ├── handler.go
        │   ├── init_test.go
        │   ├── namespace_test.go
        │   ├── project.go
        │   ├── project_test.go
        │   ├── runner.go
        │   ├── task.go
        │   ├── task_options.go
        │   ├── test
        │   │   ├── bar.txt
        │   │   ├── foo.cmd
        │   │   ├── foo.sh
        │   │   ├── foo.txt
        │   │   ├── sub
        │   │   │   ├── foo.txt
        │   │   │   ├── sub
        │   │   │   │   ├── subsub1.txt
        │   │   │   │   └── subsub2.html
        │   │   │   ├── sub1.txt
        │   │   │   └── sub2.txt
        │   │   └── templates
        │   │       └── 1.go.html
        │   ├── util
        │   │   ├── doc.go
        │   │   ├── fs.go
        │   │   ├── logging.go
        │   │   ├── prompt.go
        │   │   └── utils.go
        │   ├── waitgroup.go
        │   ├── watch_test.go
        │   └── watcher
        │       ├── fileEvent.go
        │       ├── fswatch
        │       │   ├── ISSUES
        │       │   ├── LICENSE
        │       │   ├── README.md
        │       │   ├── clinotify
        │       │   │   └── clinotify.go
        │       │   ├── doc.go
        │       │   ├── fswatch.go
        │       │   ├── watch_item.go
        │       │   └── watcher.go
        │       └── watcher.go
        └── yaml.v2
            ├── LICENSE
            ├── LICENSE.libyaml
            ├── README.md
            ├── apic.go
            ├── decode.go
            ├── decode_test.go
            ├── emitterc.go
            ├── encode.go
            ├── encode_test.go
            ├── parserc.go
            ├── readerc.go
            ├── resolve.go
            ├── scannerc.go
            ├── sorter.go
            ├── suite_test.go
            ├── writerc.go
            ├── yaml.go
            ├── yamlh.go
            └── yamlprivateh.go
```

The thing I've noticed noticed here is that my `go-findroot` package isn't found at all now (I'm guessing because it's not appearing in my glide.lock or glide.yaml files (as it's a sub dependency within `go-elasticache`)

**Comment by Integralist** [comment]
So I've decided to delete my `glide.lock` and my `vendor` directory (note: my application isn't within the root of my project's directory, it's instead within a `src` folder and inside _that_ folder is my application code and vendor directory etc)

My `glide.yaml` looks like:

```
package: github.com/bbc/mozart-requester/src
import:
- package: github.com/julienschmidt/httprouter
- package: gopkg.in/yaml.v2
- package: gopkg.in/godo.v2
- package: github.com/joho/godotenv
- package: github.com/integralist/go-elasticache
- package: github.com/bbc/mozart-api-common
```

I've run `glide install` from inside my `src` folder and I can see the following output:

```
[INFO] Lock file (glide.lock) does not exist. Performing update.
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/julienschmidt/httprouter.
[INFO] Fetching updates for gopkg.in/yaml.v2.
[INFO] Fetching updates for github.com/joho/godotenv.
[INFO] Fetching updates for github.com/integralist/go-elasticache.
[INFO] Fetching updates for github.com/bbc/mozart-api-common.
[INFO] Fetching updates for gopkg.in/godo.v2.
[INFO] Resolving imports
[INFO] Found Godeps.json file in vendor/github.com/bbc/mozart-api-common
[INFO] Fetching github.com/bradfitz/gomemcache/memcache into /Users/M/Projects/golang/src/github.com/bbc/mozart-requester/src/vendor
[INFO] Fetching github.com/integralist/go-findroot/find into /Users/M/Projects/golang/src/github.com/bbc/mozart-requester/src/vendor
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references for remaining imports
[INFO] Project relies on 8 dependencies.
```

My `glide.lock` now looks like:

```
hash: 9a195b8f2fed77bdbeaffae53286bc2f34262ca3d3116bdd889a0f57ca624528
updated: 2016-05-18T13:59:06.665086971+01:00
imports:
- name: github.com/bbc/mozart-api-common
  version: e18f7db9f9614f35bd01b52259c4da8bb557b539
  subpackages:
  - logger
  - Godeps/_workspace/src/github.com/Sirupsen/logrus
  - Godeps/_workspace/src/gopkg.in/alexcesaro/statsd.v1
- name: github.com/bradfitz/gomemcache
  version: fb1f79c6b65acda83063cbc69f6bba1522558bfc
  subpackages:
  - memcache
- name: github.com/integralist/go-elasticache
  version: 98137cc2d86f06f5300c01d9d71b57fe72923498
  subpackages:
  - elasticache
- name: github.com/integralist/go-findroot
  version: ac90681525dc30c2163cc606675922b7fdb9c041
  subpackages:
  - find
- name: github.com/joho/godotenv
  version: 4ed13390c0acd2ff4e371e64d8b97c8954138243
- name: github.com/julienschmidt/httprouter
  version: 77366a47451a56bb3ba682481eed85b64fea14e8
- name: gopkg.in/godo.v2
  version: b5fd2f0bef1ebe832e628cfad18ab1cc707f65a1
- name: gopkg.in/yaml.v2
  version: a83829b6f1293c91addabc89d0571c246397bbf4
devImports: []
```
