### ISSUE TITLE
When vcs set but no repo used the vcs is skipped

### ISSUE THREAD

**Issue by mattfarina** [Masterminds/glide#46]
When in the yaml file the vcs is set but the repo isn't the vcs is skipped and `go get` is used instead. You can see this at https://github.com/Masterminds/glide/blob/8bd36c1a62fd1b145b3b63b7495c74c099fe84b6/cmd/get_imports.go#L196.

For example, the following will use `go get` instead of git:
```
package: foo
import:
  - package: github.com/codegangsta/cli
    vcs: git
```
For git to be used you would need,
```
package: foo
import:
  - package: github.com/codegangsta/cli
    vcs: git
    repo: https://github.com/codegangsta/cli
```

@technosophos before I make changes to this, was this intentional?
