### ISSUE TITLE
Package aliasing does not work in some situations

### ISSUE THREAD

**Issue by gsalgado** [Masterminds/glide#5]
I'm giving glide a try and I encountered a problem when aliasing packages. In the example below I've aliased the btcws pkg to a specific repo/branch, and then I have another dependency (btcrpcclient, not aliased) which depends on btcws. IIUC, glide will first clone btcws (from the appropriate repo), but leave it in the master branch instead of switching to the branch I've specified. Then it moves on to installing btcrpcclient (using go get), but that will cause it to be built against the btcws/master, which will fail because that is not the branch I wanted to use. This can be reproduced by running 'glide install' with the given glide.yaml

===== glide.yaml ======

``` yaml
package: main

import:
  - package: github.com/conformal/btcws
    repo: git@github.com:/monetas/btcws
    vcs: git
    ref: no-import-path-modifications
  - package: github.com/conformal/btcrpcclient
```

==== glide install =====

[INFO] Installing github.com/conformal/btcws with Git (From git@github.com:/monetas/btcws)
[INFO] Git: Cloning into '/tmp/bar/_vendor/src/github.com/conformal/btcws'...
[INFO] Installing github.com/conformal/btcrpcclient with 'go get'
[WARN] Go Get: # github.com/conformal/btcrpcclient
_vendor/src/github.com/conformal/btcrpcclient/notify.go:758: cannot use outpoint (type *"github.com/conformal/btcwire".OutPoint) as type *"github.com/monetas/btcwire".OutPoint in function argument
_vendor/src/github.com/conformal/btcrpcclient/notify.go:983: cannot use op (type *"github.com/conformal/btcwire".OutPoint) as type *"github.com/monetas/btcwire".OutPoint in function argument
_vendor/src/github.com/conformal/btcrpcclient/notify.go:1068: cannot use op (type *"github.com/conformal/btcwire".OutPoint) as type *"github.com/monetas/btcwire".OutPoint in function argument
[WARN] Skipped getting github.com/conformal/btcrpcclient: exit status 2
[INFO] Settting version of github.com/conformal/btcws to no-import-path-modifications
