### ISSUE TITLE
testImports doesn't handle repo: attribute

### ISSUE THREAD

**Issue by ansel1** [Masterminds/glide#514]
Had this under testImport: section of glide.yaml:

```yaml
- package: github.com/stretchr/testify
  repo: https://github.com/ansel1/testify.git
  subpackages:
  - assert
  - require
```
glide up would complain that version could not be found in github.com/stretchr/testify. If I move that stanza into import: section, it works.

**Comment by franciscocpg** [comment]
hi @ansel1. Which glide version are you using?

**Comment by franciscocpg** [comment]
Well, you complain about `testImport: section`, so you must be using `0.11.0`.

**Comment by mattfarina** [comment]
@ansel1 are you directly importing this in your test files or is one of your test files importing it?

**Comment by ansel1** [comment]
:) I don't think I understand that question.  Do you mean, is it a first-order dependencies of my tests, or a transitive dependency of my tests?  It's a first-order dependency.  Most of by *_test.go files directly import "github.com/stretchr/testify/assert" or "github.com/stretchr/testify/require".  

They don't import the parent package ("github.com/stretchr/testify").  Not sure if that matters.

**Comment by mattfarina** [comment]
@ansel1 you answered my question. thanks.

I'm looking to get a 0.11.1 release out soon. I'd like to get this fixed and in that release.

**Comment by ansel1** [comment]
awesome, thanks

**Comment by mattfarina** [comment]
@ansel1 I'm having trouble reproducing this. Using the tip of master for Glide I see....

```sh
mfarina in ~/Code/go/src/github.com/Masterminds/example/vendor/github.com/stretchr/testify on master
± git remote -v
origin	https://github.com/ansel1/testify.git (fetch)
origin	https://github.com/ansel1/testify.git (push)
```

I copied and pasted your snippet. The only thing I noticed is that it's `testImport` and not `testImports`.

My exact section looks like:
```yaml
testImport:
- package: github.com/stretchr/testify
  repo: https://github.com/ansel1/testify.git
  subpackages:
  - assert
  - require
```

I updated the `glide.yaml` file and then ran `glide up`.

Can you help me reproduce this?
