### ISSUE TITLE
Glide not installing all dependencies of Gin (Godep based)

### ISSUE THREAD

**Issue by robvdl** [Masterminds/glide#525]
If I create a simple glide.yaml file that imports Gin;

import:
  - package: github.com/gin-gonic/gin

Then do a "glide up", compile my app, I get the error that two of the dependencies listed in Gin's Godep.json file lists are not installed:

github.com/golang/protobuf/proto and gopkg.in/go-playground/validator.v8

These packages are clearly listed in the Godeps/Godeps.json file in the GIN repository, so why then if I include Gin in my poroject and do a "glide up" do I not get these two packages installed.  I thought Glide could handle Godeps projects, but it doesn't look like it is working for Gin, is this a bug? or am I doing something wrong?

It appears I need to re-list the dependencies that Gin lists in it's Godeps.json file, this seems wrong to me.

**Comment by jonbo** [comment]
I ran into the exact issue myself with Gin. It appears Glide fails to retrieve dependencies of the dependency (Gin, in this case) if it wasn't already imported in your project at the time of first installing it with 'glide up'. 

A follow-up 'glide up' should fix it (assuming you have it imported now) and retrieve those missing dependencies.

(This was my issue/solution anyway.)

**Comment by marioluan** [comment]
Same here. I had to add gin's dependencies to my own project in order to make it work.

**Comment by robvdl** [comment]
Ah thank you for this, so it definitely is a bug, it isn't just me :) also good there is a workaround for now.

**Comment by mattfarina** [comment]
Using the tip of master I cannot reproduce this problem with the following:

**main.go:**
```go
package main

import (
	"fmt"

	_ "github.com/gin-gonic/gin"
)

func main() {
	fmt.Println("test")
}
```

**glide.yaml:**
```yaml
package: foo
import:
- package: github.com/gin-gonic/gin
```

**glide.lock:**
```yaml
hash: 1b9c474483dd1c98724d72487cacd0dc3fa6cd0f876bb422b44779250d66b6f3
updated: 2016-08-30T20:59:16.182465175-04:00
imports:
- name: github.com/gin-gonic/gin
  version: f931d1ea80ae95a6fc739213cdd9399bd2967fb6
  subpackages:
  - binding
  - render
- name: github.com/golang/protobuf
  version: 2402d76f3d41f928c7902a765dfc872356dd3aad
  subpackages:
  - proto
- name: github.com/manucorporat/sse
  version: ee05b128a739a0fb76c7ebd3ae4810c1de808d6d
- name: golang.org/x/net
  version: f315505cf3349909cdf013ea56690da34e96a451
  subpackages:
  - context
- name: gopkg.in/go-playground/validator.v8
  version: c193cecd124b5cc722d7ee5538e945bdb3348435
- name: gopkg.in/yaml.v2
  version: e4d366fc3c7938e2958e662b4258c7a89e1f0e3e
testImports: []
```

You'll notice both `github.com/golang/protobuf/proto` and `gopkg.in/go-playground/validator.v8` are present and they are in the `vendor/` directory.

Can you provide me a way to reproduce this?
