### ISSUE TITLE
Wrongly pinned deps

### ISSUE THREAD

**Issue by abourget** [Masterminds/glide#61]
with `glide.yaml`:

```
package: main
import:
  - package: golang.org/x/net
  - package: github.com/gorilla/context
  - package: code.google.com/p/cascadia
  - package: github.com/codegangsta/negroni
  - package: github.com/PuerkitoBio/goquery
  - package: github.com/gorilla/mux
  - package: github.com/boltdb/bolt
  - package: bitbucket.org/kardianos/osext
  - package: github.com/GeertJohan/go.rice
  - package: github.com/daaku/go.zipexe
  - package: code.google.com/p/go.net
```

running `glide pin` outputs:

```
$ glide pin
[WARN] Could not get commit on code.google.com/p/cascadia: Cannot detect VCS[WARN] Could not get commit on bitbucket.org/kardianos/osext: exit status 255[WARN] Could not get commit on code.google.com/p/go.net: exit status 255package: main
import:
  - package: golang.org/x/net
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/gorilla/context
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: code.google.com/p/cascadia
  - package: github.com/codegangsta/negroni
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/PuerkitoBio/goquery
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/gorilla/mux
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/boltdb/bolt
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: bitbucket.org/kardianos/osext
  - package: github.com/GeertJohan/go.rice
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: github.com/daaku/go.zipexe
    ref:     02bd0106d0bd3446662aa7069b5c4afcb15b9df2
  - package: code.google.com/p/go.net
```

It happens that `02bd0106...` is actually the git commit of the current repo, and not of any of the dependencies.

Also, notice the WARNings which are all on the same line.. difficult to read :)
