### ISSUE TITLE
Update failed for google.golang.org/cloud: The Remote does not match the VCS endpoint

### ISSUE THREAD

**Issue by Cedric-Venet** [Masterminds/glide#612]
With a glide version from just a moment ago, try to do a `glide get google.golang.org/cloud/storage` or to add
```
- package: google.golang.org/cloud
```
to my glide.yaml and doing `glide update`  result in those error:
```
[ERROR] Update failed for google.golang.org/cloud: The Remote does not match the VCS endpoint                                                                                    
[ERROR] Failed to do initial checkout of config: The Remote does not match the VCS endpoint 
```

any idea what the issue is?

I manage to make it work by manually setting the repo, but go get does not have this issue:
```
- package: google.golang.org/cloud
  repo: https://github.com/GoogleCloudPlatform/google-cloud-go
```

**Comment by kujenga** [comment]
@Cedric-Venet If you aren't already aware of this change, there was a post documenting the switch from `google.golang.org/cloud` to `cloud.google.com/go` here: https://groups.google.com/forum/#!topic/google-api-go-announce/nXY-DYZGqz8

The legacy endpoints at `google.golang.org/cloud` were removed on the 12th according to that post. Most likely, this isn't an issue with glide and you just need to update the references in your code.

**Comment by Cedric-Venet** [comment]
Indeed, sorry for the noise then. And Thanks for the information. (they did not put anything in the doc or github page through...)

**Comment by kujenga** [comment]
Yeah, it definitely seemed like it could have been communicated better, I didn't see it referenced anywhere other than that one mailing list post....

**Comment by seh** [comment]
I'm still getting bitten by something similar today:
> [WARN]	Unable to checkout cloud.google.com/go
> [ERROR]	Update failed for cloud.google.com/go: Cannot detect VCS

I see the following in my _glide.yaml_ file:
```yaml
- package: cloud.google.com/go
  version: 9c1098a4debc9bf1073ed0e4872b12bd916243d8
  repo: https://code.googlesource.com/gocloud
  subpackages:
  - compute/metadata
  - internal
```
I can reach the URL _https://cloud.google.com/go?go-get=1_ without any problem, and I do see that it offers [a remote import `meta` element](https://golang.org/cmd/go/#hdr-Remote_import_paths).
```html
<meta name="go-import" content="cloud.google.com/go git https://code.googlesource.com/gocloud">
```
Ah, now I see: Glide can't tell which VCS to use. Adding [the `vcs` key](https://glide.readthedocs.io/en/latest/glide.yaml/) did the trick:
```yaml
- package: cloud.google.com/go
  version: 9c1098a4debc9bf1073ed0e4872b12bd916243d8
  repo: https://code.googlesource.com/gocloud
  vcs: git
  subpackages:
  - compute/metadata
  - internal
```

**Comment by kujenga** [comment]
@seh Just as a data point for you, none of our codebases specify the `repo` or `vcs` keys. I'm not super familiar with the way the redirects all work and you may have already tried this, but perhaps if you just take both those out it works fine? e.g.

```yaml
- package: cloud.google.com/go
  version: 9c1098a4debc9bf1073ed0e4872b12bd916243d8
  subpackages:
  - compute/metadata
  - internal
```
