### ISSUE TITLE
How to compatible git remote url with ssh instead of https url?

### ISSUE THREAD

**Issue by rogerdehe** [Masterminds/glide#621]
Some of my dependency is in my local `gitlab`, if I use `https`, it will need `Username` and `Password`, so I choose to use `ssh`.
HTTPS like this:

	[remote "origin"]
		url = https://git.dayu.com/grpc_gen/ad_system_gen_go.git
		fetch = +refs/heads/*:refs/remotes/origin/*

SSH like this:

	[remote "origin"]
		url = git@git.dayu.com:grpc_gen/ad_system_gen_go.git
		fetch = +refs/heads/*:refs/remotes/origin/*

but my `glide.yaml` is like this:

	package: git.dayu.com/grpc_data_provider/admin_web_api.git
	import:
	- package: git.dayu.com/grpc_gen/ad_system_gen_go.git

It must be `HTTPS`

**Comment by hyPiRion** [comment]
Have a look at the [documentation on glide.yaml](https://glide.readthedocs.io/en/latest/glide.yaml/).

The short story is that you can include `repo`, which will be the remote repository location. In your case, that would be

```yaml
package: git.dayu.com/grpc_data_provider/admin_web_api
import:
- package: git.dayu.com/grpc_gen/ad_system_gen_go
  repo: git@git.dayu.com:grpc_gen/ad_system_gen_go.git
```
