### ISSUE TITLE
Convert glide.yaml to use a map for dependencies

### ISSUE THREAD

**Issue by sdboyer** [Masterminds/glide#641]
The latest version of gps, `v0.12.0`, has the manifest [returning a map of dependency constraints](https://godoc.org/github.com/sdboyer/gps#Manifest), rather than a slice. This makes duplicate declarations structurally impossible, which were never something glide wanted to support anyway. 👍 👍 

Now, we need to take advantage of this change by converting the `glide.yaml` from using a list to using a map/dict-type. (This is alongside a few other changes to `glide.yaml` that are already present in the `gps-integration` branch). Here's what this change should look like:

glide's own `glide.yaml` before mappifying:
```yaml
package: github.com/Masterminds/glide
homepage: https://glide.sh
license: MIT
owners:
- name: Matt Butcher
  email: technosophos@gmail.com
  homepage: http://technosophos.com/
- name: Matt Farina
  email: matt@mattfarina.com
  homepage: https://www.mattfarina.com/
dependencies:
- package: gopkg.in/yaml.v2
  branch: v2
- package: github.com/Masterminds/vcs
  version: ^1.8.0
- package: github.com/codegangsta/cli
  version: ^1.16.0
- package: github.com/Masterminds/semver
  branch: 2.x
- package: github.com/sdboyer/gps
  branch: master
```

and after:
```yaml
package: github.com/Masterminds/glide
homepage: https://glide.sh
license: MIT
owners:
- name: Matt Butcher
  email: technosophos@gmail.com
  homepage: http://technosophos.com/
- name: Matt Farina
  email: matt@mattfarina.com
  homepage: https://www.mattfarina.com/
dependencies:
    gopkg.in/yaml.v2:
        branch: v2
    github.com/Masterminds/vcs:
        version: ^1.8.0
    github.com/codegangsta/cli:
        version: ^1.16.0
    github.com/Masterminds/semver:
        branch: 2.x
    github.com/sdboyer/gps:
        branch: master
```

The "before" will be a bit unfamiliar, but glide already has logic to autoconvert from legacy (<=`v0.12.x`) `glide.yaml` files to the "before" format. We're just extending that change a little bit more.

Specifically, here's what needs to be done:

- [ ] Update the `cfg.Config` type to use a map (specifically, a [`gps.ProjectConstraints`](https://godoc.org/github.com/sdboyer/gps#ProjectConstraints)) instead of a slice for its `Imports` and `DevImports` properties. (in `cfg/config.go` - the `gpsifyDeps()` func demonstrates what this conversion looks like)
- [ ] Update the tests to deal with this new definition of the `cfg.Config` type.
- [ ] Update the YAML marshaling/unmarshaling to read and write the map correctly, in accordance with the "after" YAML above
- [ ] Update the legacy converter to write to the new `cfg.Config` field type.
- [ ] Update the legacy converter tests to accommodate the new types.
- [ ] Clean up any now-crufty logic that does deduping work.
