### ISSUE TITLE
bitbucket problem ?

### ISSUE THREAD

**Issue by gedw99** [Masterminds/glide#65]
i am using bitbucket.
i am importing github repos and glide is saving the config and putting the code in the "vendor" folder.
when i git push to bitbucket all is good.

But then i tried a git clone to a new dir from bitbucket.
when i run "glide update", it does NOT pull the code from the vendored github repo's.

Is there something i am missing ?

**Comment by mattfarina** [comment]
It should be working. Can you provide any error messages? Is your project in the `GOPATH` and you have the environment variable `GO15VENDOREXPERIMENT=1`? Do you have an example?

**Comment by gedw99** [comment]
its says its is getting them, but just does not. 

Yes i have GO15VENDOREXPERIMENT="1"
i am on go 1.5.

My code is private, so i cant make it public.
But a simple bitbucket repo, where the code has a reference to a github repo should show the problem.

**Comment by technosophos** [comment]
Can you post a redacted `glide.yaml`? Particularly, if `ref` is set to a particular commit, then Glide will update the repo, but stay checked out on commit `ref`.

**Comment by gedw99** [comment]
here is the glide file

package: main
import:
  - package: github.com/pilu/traffic
    repo:    https://github.com/pilu/traffic
    vcs:     git
  - package: github.com/pilu/config
    repo:    https://github.com/pilu/config
    vcs:     git
  - package: github.com/Unknwon/bra
    repo:    https://github.com/Unknwon/bra
    vcs:     git

**Comment by mattfarina** [comment]
I took that yaml file and created a package with a `glide.yaml` file at https://bitbucket.org/mattfarina/glide-bitbucket-example. When I run `glide up` from the root of this code (when it's cloned to `$GOPATH/src/bitbucket.net/mattfarina/glide-bitbucket-example`) it just worked.

I can't seem to replicate the problem. Can you provide some more detail?

**Comment by gedw99** [comment]
Mhhh
I looked at your test bitbucket repo.
It does not show any vendored referecnes to github projects.
Mine does have vendored code that points to github.

Maybe this is worth trying ?

**Comment by mattfarina** [comment]
@gedw99 If you look at the [glide.yaml](https://bitbucket.org/mattfarina/glide-bitbucket-example/src/962d0d049cf3bfb84b20517e8547ea18b2ad1039/glide.yaml?at=master) file in the repo you'll see github projects.

```yaml
package: main
import:
  - package: github.com/pilu/traffic
    repo:    https://github.com/pilu/traffic
    vcs:     git
  - package: github.com/pilu/config
    repo:    https://github.com/pilu/config
    vcs:     git
  - package: github.com/Unknwon/bra
    repo:    https://github.com/Unknwon/bra
    vcs:     git
```
