### ISSUE TITLE
Package aliases for the same repo cause incorrect vendor contents

### ISSUE THREAD

**Issue by carolynvs** [Masterminds/glide#659]
I am referencing different branches from the same repo, using a package alias (apologies, that may not be the right term) to differentiate between the two. After updating from glide 0.11 to 0.12, this results in both package directories under vendor containing the same files, i.e. the wrong commit.

Here are the relevant portions of my existing glide.yaml and glide.lock files: 

**glide.yaml**

```yaml
- package: github.com/getcarina/libcarina
  version: make-coe
  repo: https://github.com/getcarina/libcarina.git
  vcs: git
- package: github.com/getcarina/libmakeswarm
  version: make-swarm
  repo: https://github.com/getcarina/libcarina.git
  vcs: git
```

**glide.lock**

```yaml
- name: github.com/getcarina/libcarina
version: 0adbb72d11bbe56450ccc3f8be28d78811b8a953
repo: https://github.com/getcarina/libcarina.git
vcs: git
- name: github.com/getcarina/libmakeswarm
version: d0906762e0cc6218a6d7255567a6911121a70a83
repo: https://github.com/getcarina/libcarina.git
vcs: git
```

On glide 0.11, after running `glide install`, `vendor/github.com/getcarina/libcarina` and `vendor/github.com/getcarina/libmakeswarm` contain a different set of files, corresponding to the hashes in the lock file.

On glide 0.12+, after running `glide install`, the contents of the directories are the same. Also `.git` directory is no longer present in those vendor directories, but I assume that's a side effect of the new caching feature and not part of the problem.

This is my guess as to what is happening:
* The cache directory is keyed off of the repository, and not the package
* Glide updates the cache for a package
* Glide then updates the cache for the package alias, in the same directory (since they both are from the same repo)
* Glide then copies that single cache directory to both package directories under vendor

Thanks for writing glide! It is great and makes my go development experience so much better! 😄
