### ISSUE TITLE
locking to branch?

### ISSUE THREAD

**Issue by vpol** [Masterminds/glide#688]
Is it possible to pin specific branch for repository?

Something like:
```
- package: github.com/stretchr/testify
  branch: dev
  subpackages:
  - assert
```

**Comment by franciscocpg** [comment]
Hi @vpol 
Yes
Take a look at this [doc](https://github.com/Masterminds/glide/blob/master/docs/glide.yaml.md) and take note of this:
`version: A semantic version, semantic version range, branch, tag, or commit id to use. For more information see the versioning documentation.`
So this should work
```yaml
package: github.com/stretchr/testify
  version: dev
  subpackages:
  - assert
```
If you are using a fork then you should also use the `repo` config.
