### ISSUE TITLE
Protobuf library not being imported properly

### ISSUE THREAD

**Issue by F21** [Masterminds/glide#689]
One of my project requires the dependency `github.com/golang/protobuf/proto`.

I ran `glide init` and it created the following `glide.yaml`:
```yaml
package: github.com/Boostport/avatica
import:
- package: github.com/golang/protobuf
  subpackages:
  - proto
- package: github.com/hashicorp/go-cleanhttp
- package: github.com/satori/go.uuid
  version: ^1.1.0
- package: golang.org/x/net
  subpackages:
  - context
  - context/ctxhttp
```

However, after running `glide install`, it does not install `google.golang.org/genproto/protobuf`, which is required by the protobuf library here: https://github.com/golang/protobuf/blob/master/descriptor/descriptor.go#L46

This is the `glide.lock` file that was generated:

```yaml
hash: 741753b4dd07d3f7fb279d23825082396dc77da38532eb21c4329235233bf26e
updated: 2016-11-25T10:27:38.876164+11:00
imports:
- name: github.com/golang/protobuf
  version: 8ee79997227bf9b34611aee7946ae64735e6fd93
  subpackages:
  - proto
- name: github.com/hashicorp/go-cleanhttp
  version: ad28ea4487f05916463e2423a55166280e8254b5
- name: github.com/satori/go.uuid
  version: 879c5887cd475cd7864858769793b2ceb0d44feb
- name: golang.org/x/net
  version: 4971afdc2f162e82d185353533d3cf16188a9f4e
  subpackages:
  - context
  - context/ctxhttp
testImports: []
```
