### ISSUE TITLE
`glide get foo` does not get dependencies of `foo`

### ISSUE THREAD

**Issue by dt** [Masterminds/glide#690]
In an empty directory, I ran 
```
glide init
glide get --all-dependencies github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
```
However, after that, `go build ./vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway` fails because `protoc-gen-grpc-gateway` imports `github.com/golang/glog`, but `glog` isn't vendored.

my `glide.yaml` looks as expected:
```
package: github.com/dt/demo
import:
- package: github.com/grpc-ecosystem/grpc-gateway
  subpackages:
  - protoc-gen-grpc-gateway
```
but my glide.lock doesn't have any transitive dependencies in it:
```
hash: 961f8518d0ae0c9ad9e6af0d491e0a401e22da89e9f39496d377c8c2ed58eb7d
updated: 2016-11-28T21:17:18.379915053Z
imports:
- name: github.com/grpc-ecosystem/grpc-gateway
  version: 84398b94e188ee336f307779b57b3aa91af7063c
  subpackages:
  - protoc-gen-grpc-gateway
testImports: []
```
