### ISSUE TITLE
the repo option doesn't work anymore...

### ISSUE THREAD

**Issue by talbright** [Masterminds/glide#700]
> repo: If the package name isn't the repo location or this is a private repository it can go here. The package will be checked out from the repo and put where the package name specifies. This allows using forks.

Given a configuration like:

```yaml
- package: github.com/talbright/go-curator
  version: dfe086dc8539a7b6e1257ec11708aaa43a8a59e9
  repo: git@github.com:talbright/go-curator.git
  vcs: git
```

Glide no longer checks out from the repo -- that is to say the package is in vendor but its not a clone with a .git directory anymore. Worked fine with glide  v0.10.2
