### ISSUE TITLE
Install go-gonic/gin from gopkg, found both gin package from github and gopkg

### ISSUE THREAD

**Issue by goofansu** [Masterminds/glide#716]
glide.yaml

``` yaml
package: github.com/repong/wego
import:
- package: github.com/repong/hardict
- package: gopkg.in/gin-gonic/gin.v1
  version: ~1.1.4
```

glide.lock
```
hash: 7dc14641c547ed47620dbdd9766a439e02c7d14f39f2367da524aa40ae281c9f
updated: 2016-12-15T17:50:12.016768871+08:00
imports:
- name: github.com/adamzy/cedar-go
  version: d348c21f72432c2b6d5f05f68759fde94f64b227
- name: github.com/gin-gonic/gin
  version: e2212d40c62a98b388a5eb48ecbdcf88534688ba
  subpackages:
  - binding
  - render
- name: github.com/golang/protobuf
  version: 2402d76f3d41f928c7902a765dfc872356dd3aad
  subpackages:
  - proto
- name: github.com/huichen/sego
  version: d06fe1b3abe3877ab593b57e5e43daf6c4c25add
- name: github.com/manucorporat/sse
  version: ee05b128a739a0fb76c7ebd3ae4810c1de808d6d
- name: github.com/mattn/go-isatty
  version: 30a891c33c7cde7b02a981314b4228ec99380cca
- name: github.com/repong/hardict
  version: 473f7a4505ebb1e8347f4375055dac47558b80b5
- name: golang.org/x/net
  version: f315505cf3349909cdf013ea56690da34e96a451
  subpackages:
  - context
- name: golang.org/x/sys
  version: d75a52659825e75fff6158388dddc6a5b04f9ba5
  subpackages:
  - unix
- name: gopkg.in/gin-gonic/gin.v1
  version: e2212d40c62a98b388a5eb48ecbdcf88534688ba
- name: gopkg.in/go-playground/validator.v8
  version: c193cecd124b5cc722d7ee5538e945bdb3348435
- name: gopkg.in/yaml.v2
  version: a5b47d31c556af34a302ce5d659e6fea44d90de0
testImports: []
```

There are both `gopkg.in/gin-gonic/gin.v1` and `github.com/gin-gonic/gin` with the same commit id  and contents.

This cause `goimports` to always import `github.com/gin-gonic/gin` while I want to import `gopkg.in/gin-gonic/gin.v1`.

FYI, glide is `v0.12.3`.
