### ISSUE TITLE
Failed to generate lock file when same package exists in import and testImport

### ISSUE THREAD

**Issue by piotrkowalczuk** [Masterminds/glide#741]
On `glide install` (glide version 0.13.0-dev) I'm getting such error:

```Failed to generate lock file: Generating lock produced conflicting versions of github.com/stretchr/testify. import (~1.1.4), testImport (~1.1.0)```

Tell me if I'm wrong, but expected behavior would be to choose `~1.1.4`.

Cheers

**Comment by sagikazarmark** [comment]
I have a similar issue: `Failed to generate lock file: Generating lock produced conflicting versions of google.golang.org/grpc. import (), testImport (^1.0.5)` (Yes, it's ONLY a dev dep)

``` yaml
import:
- package: github.com/Sirupsen/logrus
  version: ^0.11.2
testImport:
- package: google.golang.org/grpc
  version: ^1.0.5
```
