### ISSUE TITLE
repo option ignored

### ISSUE THREAD

**Issue by Quiark** [Masterminds/glide#773]
There is a project where I need to use a different git repository for one dependency. That's where `repo` option under a package comes in, right? Unfortunately, glide completely ignores this.

* Tried using latest git master glide version
* Tried clearing `~/.glide`
* Later I found that the `repo` option is probably not parsed.

Example `glide.yaml`:

```yaml
package: github.com/eris-ltd/eris-db
import:
- package: github.com/eris-ltd/eris-logger
  repo: https://quiark@bitbucket.org/aslab/eris-logger.git
```
