### ISSUE TITLE
bash on windows has error

### ISSUE THREAD

**Issue by freshcn** [Masterminds/glide#778]
I use glide in bash on windows. when i exec `glide install`.i got the follow error message
```shell
[INFO]  --> Exporting golang.org/x/net
[INFO]  --> Exporting golang.org/x/crypto/acme/autocert
[INFO]  --> Exporting golang.org/x/crypto
[INFO]  Replacing existing vendor dependencies
[ERROR] remove /tmp/glide-vendor220918663/vendor/github.com/google/go-github/github: directory not empty
[ERROR] Unable to export dependencies to vendor directory: remove /mnt/c/Users/Administrator/go/src/github.com/freshcn/go-id-builder/vendor/github.com/google/go-github/github: directory not empty
```
there has the same error on  v0.12.3 and 0.13.0-dev

**Comment by bacongobbler** [comment]
do you have an example glide.yaml and glide.lock that can reproduce this failure?

**Comment by freshcn** [comment]
this is my glide.yaml and glide.lock. they can work on ubuntu and mac.

glide.yaml

```yaml
package: git.coding.net/dolist/api.git
import:
- package: github.com/freshcn/async
- package: github.com/freshcn/log
- package: github.com/freshcn/tools
  subpackages:
  - uuid
  - vaildate
- package: github.com/go-sql-driver/mysql
  version: ^1.2.0
- package: github.com/go-xorm/core
  version: ^0.5.6
- package: github.com/go-xorm/xorm
  version: ^0.5.6
- package: github.com/namsral/flag
- package: gopkg.in/ini.v1
  version: ^1.21.1
- package: gopkg.in/iris-contrib/middleware.v5
  version: ^5.0.0
  subpackages:
  - logger
- package: gopkg.in/kataras/iris.v5
  version: ^5.0.0
- package: gopkg.in/redis.v5
  version: ^5.0.1
```

glide.lock

```yaml
hash: f3c7280548e096dae033969bab54d1ebd8925c7bb7bd1758ba5b223b78b5f9f0
updated: 2017-02-18T02:01:18.477596607+08:00
imports:
- name: github.com/fatih/structs
  version: dc3312cb1a4513a366c4c9e622ad55c32df12ed3
- name: github.com/freshcn/async
  version: c3953276c8fc222c13d454dee39e2eed6ba3f5ed
- name: github.com/freshcn/log
  version: 98911aaee264b8c69ffa041c63a71574d951c8bc
- name: github.com/freshcn/tools
  version: cdcebbb7db5ed8db845c644c4e9197e11778a0d5
  subpackages:
  - uuid
  - vaildate
- name: github.com/geekypanda/httpcache
  version: 76ba6c68462ae362cda7564c44492b95322b363a
  subpackages:
  - internal
  - internal/fhttp
  - internal/fhttp/rule
  - internal/nethttp
  - internal/nethttp/rule
  - internal/server
- name: github.com/go-sql-driver/mysql
  version: a0583e0143b1624142adab07e0e97fe106d99561
- name: github.com/go-xorm/builder
  version: 867edcc549127f15667ece8876c3a60093c9634b
- name: github.com/go-xorm/core
  version: 5bf745d7d163f4380e6c2bba8c4afa60534dd087
- name: github.com/go-xorm/xorm
  version: d75356fc733fce7683c6d961fc2aeb16ededc8ef
- name: github.com/google/go-github
  version: f7fcf6f52ff94adf1cc0ded41e7768d2ad729972
  subpackages:
  - github
- name: github.com/google/go-querystring
  version: 9235644dd9e52eeae6fa48efd539fdc351a0af53
  subpackages:
  - query
- name: github.com/gorilla/websocket
  version: 2aff870ef83507abb46472eae82449f7a4c464c5
- name: github.com/hashicorp/go-version
  version: e96d3840402619007766590ecea8dd7af1292276
- name: github.com/imdario/mergo
  version: 50d4dbd4eb0e84778abe37cefef140271d96fade
- name: github.com/iris-contrib/formBinder
  version: 81b6a071e35797b83562caf4b3cad24dc01912dc
- name: github.com/iris-contrib/lego
  version: 095d7f6459c501cb15319aa2754afa221b81a3ec
  subpackages:
  - acme
- name: github.com/iris-contrib/letsencrypt
  version: 1a3e5c619a13b307df3b1b4da7cb7e57d2e156dd
- name: github.com/kataras/go-errors
  version: 0f977b82cc78d5d31bb75fb6f903ad9e852c8bbd
- name: github.com/kataras/go-fs
  version: c029e113d9faaf558b730f06041c8bf9545a3502
- name: github.com/kataras/go-options
  version: 23b556c1b935c594ec6d71ff81ead4dbeec3aa8d
- name: github.com/kataras/go-serializer
  version: 0bd874a15c70db74ef2e668e5eeda27041f03b81
  subpackages:
  - data
  - json
  - jsonp
  - markdown
  - text
  - xml
- name: github.com/kataras/go-sessions
  version: 697680208eb3db6a76240f2556eaa7d4909f2556
- name: github.com/kataras/go-template
  version: 457f21178102f4688603eccbb4f2e8d5ae1023bf
  subpackages:
  - html
- name: github.com/klauspost/compress
  version: 8df558b6cb6f9b445f9586446cfe7223e7d8bd6b
  subpackages:
  - flate
  - gzip
  - zlib
- name: github.com/klauspost/cpuid
  version: 09cded8978dc9e80714c4d85b0322337b0a1e5e0
- name: github.com/klauspost/crc32
  version: cb6bfca970f6908083f26f39a79009d608efd5cd
- name: github.com/microcosm-cc/bluemonday
  version: f77f16ffc87a6a58814e64ae72d55f9c41374e6d
- name: github.com/miekg/dns
  version: 58f52c57ce9df13460ac68200cef30a008b9c468
- name: github.com/namsral/flag
  version: 91bb473a91a4a5e1ea554fb8ddce84f832be9aca
- name: github.com/russross/blackfriday
  version: 5f33e7b7878355cd2b7e6b8eefc48a5472c69f70
- name: github.com/satori/go.uuid
  version: b061729afc07e77a8aa4fad0a2fd840958f1942a
- name: github.com/shurcooL/sanitized_anchor_name
  version: 1dba4b3954bc059efc3991ec364f9f9a35f597d2
- name: github.com/square/go-jose
  version: 63d7cfa0284d0bc9bf41d58f802037559c45ce8f
  subpackages:
  - cipher
  - json
- name: github.com/valyala/bytebufferpool
  version: e746df99fe4a3986f4d4f79e13c1e0117ce9c2f7
- name: github.com/valyala/fasthttp
  version: 4ee6517626b0549c4a4c85ad7b91acdec1d2af24
  subpackages:
  - fasthttpadaptor
  - fasthttputil
- name: golang.org/x/crypto
  version: bed12803fa9663d7aa2c2346b0c634ad2dcd43b7
  subpackages:
  - acme/autocert
  - ocsp
- name: golang.org/x/crypto/acme/autocert
  version: bed12803fa9663d7aa2c2346b0c634ad2dcd43b7
- name: golang.org/x/net
  version: 41bba8d80bbfab43231ffdf4c210037baae5f6a3
  subpackages:
  - context
  - html
  - html/atom
  - publicsuffix
- name: golang.org/x/time
  version: f51c12702a4d776e4c1fa9b0fabab841babae631
  subpackages:
  - rate
- name: gopkg.in/ini.v1
  version: e3c2d47c61e5333f9aa2974695dd94396eb69c75
- name: gopkg.in/iris-contrib/middleware.v5
  version: eff973db50aaea60190e75f8f5dc343f7de34b38
  subpackages:
  - logger
- name: gopkg.in/iris-contrib/websocket.v5
  version: bc14117ad25db88dd667f03170dc6db1e5c1f78f
- name: gopkg.in/kataras/go-errors.v0
  version: d2aaffdebcb40c69c4cb6a95e436430cde192435
- name: gopkg.in/kataras/go-fs.v0
  version: ecf3587588f7218a21a991a1c0a9f4bdebd20cc1
- name: gopkg.in/kataras/go-websocket.v0
  version: cb1681badd5582ccaebaf02f452e2d5a98f1a440
- name: gopkg.in/kataras/iris.v5
  version: 547c5360493789dc4f0e65894f14af086c62d03c
  subpackages:
  - utils
- name: gopkg.in/redis.v5
  version: 2fe9c5cc0a8da9faeba3a45511a4ece8f7e37dc2
  subpackages:
  - internal
  - internal/consistenthash
  - internal/hashtag
  - internal/pool
  - internal/proto
testImports: []
```

**Comment by mattfarina** [comment]
Is this bash installed with git? What windows version and bash version?

**Comment by joesteele** [comment]
I believe this is related to #654.

Using the [example docker glide.yaml](https://github.com/Masterminds/glide/issues/654#issuecomment-267159330) provided in the comments, I'm able to reproduce this on my Windows machine (on the recent Creator's Update) using the WSL (bash v4.3.11(1)-release).

Using this same `glide.yaml` on my mac laptop works fine with the same glide and go versions (glide v0.12.3 and go v1.8).

```yaml
package: .
import:
- package: github.com/docker/docker
  version: master
```
