### ISSUE TITLE
Misinterpreting main project as a subpackage

### ISSUE THREAD

**Issue by awnumar** [Masterminds/glide#824]
The issue is on [this](https://github.com/libeclipse/dissident/tree/patch/memory-security) branch.

When I run `glide init`, I get the following:

```
package: .
import:
- package: github.com/Jeffail/gabs
- package: github.com/cheggaaa/pb
- package: github.com/libeclipse/dissident // This line should be at the top.
  subpackages:
  - coffer
  - crypto
  - data
  - stdin
- package: github.com/libeclipse/memguard
- package: github.com/syndtr/goleveldb
  subpackages:
  - leveldb
- package: golang.org/x/crypto
  subpackages:
  - blake2b
  - nacl/secretbox
  - scrypt
  - ssh/terminal
```

As you can see, it labels the current package as `.` and attempts to vendor sub-packages. This is a new issue, but I'm not sure which change caused it.
