### ISSUE TITLE
Support for build tags in glide

### ISSUE THREAD

**Issue by szank** [Masterminds/glide#83]
Hi,
We are using the codec package (https://github.com/ugorji/go/tree/master/codec) in our project. 
This package can be built with a build tag. We would like to use this package compiled with the build tag. 

For go get it works like this : 
`go get -tags unsafe github.com/ugorji/go`

Is it possible to implement this ?

Regards, 
Maciej

**Comment by mattfarina** [comment]
@szank thanks for bringing this to our attention.

@technosophos I was poking at [the docs for codec](https://github.com/ugorji/go/tree/master/codec) and it does talk about using `unsafe`.

I'm wondering if build flags is a good thing to grab as a string (as opposed to something like unsafe as a bool). It could be used to also grab constraints such as the OS/Arch as well (compared to the current filter method).

Thoughts?

**Comment by technosophos** [comment]
Can someone propose how this would look in the glide.yaml file?

**Comment by szank** [comment]
Hi, 
Sorry for the late reply, somehow i go the email notification about the replies  just now. 
I am all for the string tags, example : 
```
- package: github.com/ugorji/go
    repo: https://github.com/ugorji/go
    subpackages:
        - codec
    ref: 5abd4e96a45c386928ed2ca2a7ef63e2533e18ec
    vcs: git
    tags: unsafe, amd64, etc...
```

This is the easiest way of doing things, as 
1. Tag names supported by the packages can completely arbitrary
2. It would be easy to pass the string to the build command line

I did have a look at the current filtering documentation. I didn't read the code though. 
It seems reasonable to leave filtering as is, this seems like a bit different functionality.
