### ISSUE TITLE
Glide not honoring repo and always closing from https://{{name}}

### ISSUE THREAD

**Issue by kalbasit** [Masterminds/glide#87]
glide.yaml support specifying a `repo` URL to clone from but it seems that it's not being honored unless cloning from the "guessed" URL fails. I think that if repo is present it should be honored regardless.

Use case: I made a patch to a library that I am using and while I am waiting for the PR to be merged upstream, I'd like to use my own fork without having to change the imports everywhere in the project.

glide.yaml:

```
package: github.com/kalbasit/mail-api

import:
  - package: github.com/zenhack/go.notmuch
    repo: https://github.com/kalbasit/go.notmuch.git
  - package: github.com/namsral/flag
```

yet glide clones go.notmuch from https://github.com/zenhack/go.notmuch.git rather than https://github.com/kalbasit/go.notmuch.git
