### ISSUE TITLE
how to ignore the vendor directory from dependency repos?

### ISSUE THREAD

**Issue by chenchun** [Masterminds/glide#871]
My main repo depens on k8s repo, both my repo and k8s depens on glog. If I don't delete the vendor directory in k8s repo, eg. `vendor/k8s.io/kubernetes/vendor/`, my program will run into the following error:

```
./galaxy flag redefined: log_dir
panic: ./galaxy flag redefined: log_dir

goroutine 1 [running]:
panic(0x85c140, 0xc82024a470)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
flag.(*FlagSet).Var(0xc820058060, 0x7fa71593c1e8, 0xc82024a420, 0x9f2920, 0x7, 0xa90440, 0x2f)
	/usr/local/go/src/flag/flag.go:776 +0x454
flag.(*FlagSet).StringVar(0xc820058060, 0xc82024a420, 0x9f2920, 0x7, 0x0, 0x0, 0xa90440, 0x2f)
	/usr/local/go/src/flag/flag.go:679 +0xc7
flag.(*FlagSet).String(0xc820058060, 0x9f2920, 0x7, 0x0, 0x0, 0xa90440, 0x2f, 0xc82024a410)
	/usr/local/go/src/flag/flag.go:692 +0x83
flag.String(0x9f2920, 0x7, 0x0, 0x0, 0xa90440, 0x2f, 0x7eca7a)
	/usr/local/go/src/flag/flag.go:699 +0x5f
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog.init()
	/go/src/git.code.oa.com/gaiastack/galaxy/go/src/git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog/glog_file.go:41 +0x13e
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/pkg/util/iptables.init()
	/go/src/git.code.oa.com/gaiastack/galaxy/go/src/git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/pkg/util/iptables/save_restore.go:108 +0x5e
git.code.oa.com/gaiastack/galaxy/pkg/network/portmapping.init()
	/go/src/git.code.oa.com/gaiastack/galaxy/go/src/git.code.oa.com/gaiastack/galaxy/pkg/network/portmapping/iptables.go:269 +0x63
git.code.oa.com/gaiastack/galaxy/pkg/galaxy.init()
	/go/src/git.code.oa.com/gaiastack/galaxy/go/src/git.code.oa.com/gaiastack/galaxy/pkg/galaxy/server.go:161 +0x9c
main.init()
	/go/src/git.code.oa.com/gaiastack/galaxy/go/src/git.code.oa.com/gaiastack/galaxy/cmd/galaxy/galaxy.go:27 +0x45
```

Here is the output of compiling. glog linked twice from `git.code.oa.com/gaiastack/galaxy/vendor/github.com/golang/glog` and `git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog`

```
Building galaxy
git.code.oa.com/gaiastack/galaxy/vendor/github.com/containernetworking/cni/pkg/types
git.code.oa.com/gaiastack/galaxy/vendor/github.com/containernetworking/cni/pkg/version
git.code.oa.com/gaiastack/galaxy/vendor/github.com/containernetworking/cni/pkg/invoke
git.code.oa.com/gaiastack/galaxy/vendor/github.com/containernetworking/cni/pkg/skel
git.code.oa.com/gaiastack/galaxy/pkg/network/flannel
git.code.oa.com/gaiastack/galaxy/vendor/github.com/golang/glog
git.code.oa.com/gaiastack/galaxy/pkg/api/cniutil
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/distribution/digest
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/distribution/reference
git.code.oa.com/gaiastack/galaxy/vendor/github.com/Sirupsen/logrus
git.code.oa.com/gaiastack/galaxy/vendor/github.com/opencontainers/runc/libcontainer/user
git.code.oa.com/gaiastack/galaxy/vendor/golang.org/x/net/proxy
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/go-connections/sockets
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/client/transport
git.code.oa.com/gaiastack/galaxy/vendor/golang.org/x/net/context
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/client/transport/cancellable
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/blkiodev
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/strslice
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/go-connections/nat
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/go-units
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/container
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/versions
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/filters
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/network
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/registry
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/reference
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/types/time
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/go-connections/tlsconfig
git.code.oa.com/gaiastack/galaxy/vendor/github.com/docker/engine-api/client
git.code.oa.com/gaiastack/galaxy/pkg/api/docker
git.code.oa.com/gaiastack/galaxy/pkg/api/k8s
git.code.oa.com/gaiastack/galaxy/pkg/api/galaxy
git.code.oa.com/gaiastack/galaxy/vendor/github.com/vishvananda/netns
git.code.oa.com/gaiastack/galaxy/vendor/github.com/vishvananda/netlink/nl
git.code.oa.com/gaiastack/galaxy/vendor/github.com/vishvananda/netlink
git.code.oa.com/gaiastack/galaxy/pkg/flags
git.code.oa.com/gaiastack/galaxy/pkg/wait
git.code.oa.com/gaiastack/galaxy/pkg/gc
git.code.oa.com/gaiastack/galaxy/pkg/network/kernel
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/vendor/github.com/godbus/dbus
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/pkg/util/dbus
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/pkg/util/exec
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/vendor/github.com/coreos/go-semver/semver
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/vendor/github.com/golang/glog
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/pkg/util/sets
git.code.oa.com/gaiastack/galaxy/vendor/k8s.io/kubernetes/pkg/util/iptables
git.code.oa.com/gaiastack/galaxy/pkg/network/portmapping
git.code.oa.com/gaiastack/galaxy/pkg/api/apiswitch
git.code.oa.com/gaiastack/galaxy/pkg/utils/httputils
git.code.oa.com/gaiastack/galaxy/pkg/network/remote
git.code.oa.com/gaiastack/galaxy/vendor/github.com/emicklei/go-restful/log
git.code.oa.com/gaiastack/galaxy/vendor/github.com/emicklei/go-restful
git.code.oa.com/gaiastack/galaxy/pkg/galaxy
git.code.oa.com/gaiastack/galaxy/pkg/signal
git.code.oa.com/gaiastack/galaxy/cmd/galaxy
```

I tried to use `ignore`, but the package still gets vendored in.

```
package: git.code.oa.com/gaiastack/galaxy
ignore:
- github.com/containernetworking/cni/vendor
- k8s.io/kubernetes/vendor
import:
- package: github.com/containernetworking/cni
  version: 0e09ad29df1eda8c0e15f8b6c4c7784a42e125bf
  subpackages:
  - pkg/invoke
  - pkg/ip
  - pkg/ipam
  - pkg/ns
  - pkg/skel
  - pkg/types
  - pkg/version
- package: github.com/docker/engine-api
  version: dea108d3aa0c67d7162a3fd8aa65f38a430019fd
  subpackages:
  - client
  - types
- package: github.com/emicklei/go-restful
  version: 89ef8af493ab468a45a42bb0d89a06fccdd2fb22
  subpackages:
  - log
  - swagger
- package: github.com/golang/glog
- package: github.com/vishvananda/netlink
  subpackages:
  - nl
- package: github.com/vishvananda/netns
- package: golang.org/x/net/context
- package: k8s.io/client-go
  repo: http://github.com/kubernetes/client-go.git
  version: v1.4.0
  subpackages:
  - 1.4/kubernetes
  - 1.4/pkg/api
  - 1.4/pkg/api/v1
  - 1.4/pkg/util/wait
  - 1.4/tools/cache
- package: k8s.io/kubernetes
  version: v1.4.12
  repo: http://github.com/kubernetes/kubernetes.git
  subpackages:
  - pkg/util/dbus
  - pkg/util/exec
  - pkg/util/iptables
```
