### ISSUE TITLE
Libraries that resides in subfolders can't be installed

### ISSUE THREAD

**Issue by palsivertsen** [Masterminds/glide#946]
When adding a dependency that resides in a subfolder Glide fails on install.

Example:
```yaml
package: my-project
import:
  - package: gitlab.com/company/project/libraries/my-library
    repo: git@gitlab.com/company/project/libraries/my-library.git
```

Doing `glide i` results in the following error:
```
[ERROR]	Error scanning gitlab.com/company/project/libraries/my-library: cannot find package "." in:
	/home/user/.glide/cache/src/git-gitlab.com-company-projects-libraries-my-library.git/libraries/my-library
```

Note the last line `-libraries-my-library.git/libraries/my-library` where `libraries/my-library` is treated as a subpackage.
