### ISSUE TITLE
glide install always slowly when network is unreachable

### ISSUE THREAD

**Issue by Adol1111** [Masterminds/glide#957]
golang.org is always unreachable in China. So I add repo like this:

```
package: GlideTest
import:
- package: golang.org/x/time
  repo: https://github.com/golang/time.git
  subpackages:
  - rate
```

when I execute **glide install** , it wait for 30 seconds - 1  minutes, then output "[INFO]  Downloading dependencies. Please wait..."

Then I remove import  golang.org/x/time in glide.yaml. ( just remove in glide.yaml, not glide.lock) When I execute **glide install**,  it output immediately.
