### ISSUE TITLE
"glide up" is using prerelease versions

### ISSUE THREAD

**Issue by asherlporetz** [Masterminds/glide#991]
What's the right version expression to avoid "glide up" using prerelease versions? This dependency

```yaml
- package: k8s.io/kubernetes
  version: v1.7.x
- package: github.com/prometheus/client_golang
  version: ^0.8.0
```
results in
```
[INFO]	--> Detected semantic version. Setting version for github.com/prometheus/client_golang to v0.9.0-pre1.
[INFO]	--> Detected semantic version. Setting version for k8s.io/kubernetes to v1.7.17-beta.0.
```
